language: node_js
node_js:
  - "5"
before_script:
  - "npm run lint"
script: "npm test"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
